// This file is generated by Velite

import type __vc from '../velite.config.ts'

type Collections = typeof __vc.collections

export type Blog = Collections['blog']['schema']['_output']
export declare const blog: Blog[]

export type Project = Collections['projects']['schema']['_output']
export declare const projects: Project[]
